// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Triagem.API.Data;

#nullable disable

namespace Triagem.API.Data.Migrations
{
    [DbContext(typeof(TriagemDbContext))]
    [Migration("20260824191239_OptimizeHistoryIndex")]
    partial class OptimizeHistoryIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Triagem.API.Models.FaixaResultado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<int>("PontuacaoMax")
                        .HasColumnType("int");

                    b.Property<int>("PontuacaoMin")
                        .HasColumnType("int");

                    b.Property<string>("Recomendacao")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("TriagemModeloId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TriagemModeloId");

                    b.ToTable("FaixasResultado", (string)null);
                });

            modelBuilder.Entity("Triagem.API.Models.Pergunta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TriagemModeloId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TriagemModeloId");

                    b.ToTable("Perguntas", (string)null);
                });

            modelBuilder.Entity("Triagem.API.Models.RespostaDada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PerguntaId")
                        .HasColumnType("int");

                    b.Property<int>("TriagemResultadoId")
                        .HasColumnType("int");

                    b.Property<bool>("Valor")
                        .HasColumnType("bit");

                    b.Property<string>("ValorProtegido")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("TriagemResultadoId");

                    b.ToTable("RespostasDadas", (string)null);
                });

            modelBuilder.Entity("Triagem.API.Models.TriagemModelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CriadorUsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("Icone")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Imagem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicoAlvo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CriadorUsuarioId");

                    b.ToTable("TriagemModelos", (string)null);
                });

            modelBuilder.Entity("Triagem.API.Models.TriagemResultado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Classificacao")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("DadosProtegidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("NomePaciente")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Pontuacao")
                        .HasColumnType("int");

                    b.Property<int>("PontuacaoMaxima")
                        .HasColumnType("int");

                    b.Property<string>("Recomendacao")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("TriagemModeloId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TriagemModeloId");

                    b.HasIndex("UsuarioId", "TriagemModeloId", "Data");

                    b.ToTable("TriagemResultados", (string)null);
                });

            modelBuilder.Entity("Triagem.API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Triagem.API.Models.UsuarioTriagemHome", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("TriagemModeloId")
                        .HasColumnType("int");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<bool>("Visivel")
                        .HasColumnType("bit");

                    b.HasKey("UsuarioId", "TriagemModeloId");

                    b.HasIndex("TriagemModeloId");

                    b.ToTable("UsuarioTriagensHome", (string)null);
                });

            modelBuilder.Entity("Triagem.API.Models.FaixaResultado", b =>
                {
                    b.HasOne("Triagem.API.Models.TriagemModelo", "TriagemModelo")
                        .WithMany("Faixas")
                        .HasForeignKey("TriagemModeloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TriagemModelo");
                });

            modelBuilder.Entity("Triagem.API.Models.Pergunta", b =>
                {
                    b.HasOne("Triagem.API.Models.TriagemModelo", "TriagemModelo")
                        .WithMany("Perguntas")
                        .HasForeignKey("TriagemModeloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TriagemModelo");
                });

            modelBuilder.Entity("Triagem.API.Models.RespostaDada", b =>
                {
                    b.HasOne("Triagem.API.Models.TriagemResultado", "TriagemResultado")
                        .WithMany("Respostas")
                        .HasForeignKey("TriagemResultadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TriagemResultado");
                });

            modelBuilder.Entity("Triagem.API.Models.TriagemModelo", b =>
                {
                    b.HasOne("Triagem.API.Models.Usuario", "CriadorUsuario")
                        .WithMany("TriagensCriadas")
                        .HasForeignKey("CriadorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CriadorUsuario");
                });

            modelBuilder.Entity("Triagem.API.Models.TriagemResultado", b =>
                {
                    b.HasOne("Triagem.API.Models.TriagemModelo", "TriagemModelo")
                        .WithMany()
                        .HasForeignKey("TriagemModeloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Triagem.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TriagemModelo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Triagem.API.Models.UsuarioTriagemHome", b =>
                {
                    b.HasOne("Triagem.API.Models.TriagemModelo", "TriagemModelo")
                        .WithMany()
                        .HasForeignKey("TriagemModeloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Triagem.API.Models.Usuario", "Usuario")
                        .WithMany("ConfiguracaoHome")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TriagemModelo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Triagem.API.Models.TriagemModelo", b =>
                {
                    b.Navigation("Faixas");

                    b.Navigation("Perguntas");
                });

            modelBuilder.Entity("Triagem.API.Models.TriagemResultado", b =>
                {
                    b.Navigation("Respostas");
                });

            modelBuilder.Entity("Triagem.API.Models.Usuario", b =>
                {
                    b.Navigation("ConfiguracaoHome");

                    b.Navigation("TriagensCriadas");
                });
#pragma warning restore 612, 618
        }
    }
}
