namespace MauiApp3;

// As páginas mantêm a herança nativa exigida pelo gerador XAML, mas todas as
// sobrecargas usadas pelo app são redirecionadas para o diálogo visual do Triar.
public partial class AjudaPage { public new Task<bool> DisplayAlertAsync(string t, string m, string a) => TriarDialogs.ExibirAsync(this, t, m, a); public new Task<bool> DisplayAlertAsync(string t, string m, string a, string c) => TriarDialogs.ExibirAsync(this, t, m, a, c); }
public partial class CadastroPage { public new Task<bool> DisplayAlertAsync(string t, string m, string a) => TriarDialogs.ExibirAsync(this, t, m, a); public new Task<bool> DisplayAlertAsync(string t, string m, string a, string c) => TriarDialogs.ExibirAsync(this, t, m, a, c); }
public partial class ContatoPage { public new Task<bool> DisplayAlertAsync(string t, string m, string a) => TriarDialogs.ExibirAsync(this, t, m, a); public new Task<bool> DisplayAlertAsync(string t, string m, string a, string c) => TriarDialogs.ExibirAsync(this, t, m, a, c); }
public partial class CreditosPage { public new Task<bool> DisplayAlertAsync(string t, string m, string a) => TriarDialogs.ExibirAsync(this, t, m, a); public new Task<bool> DisplayAlertAsync(string t, string m, string a, string c) => TriarDialogs.ExibirAsync(this, t, m, a, c); }
public partial class CriarTriagemPage { public new Task<bool> DisplayAlertAsync(string t, string m, string a) => TriarDialogs.ExibirAsync(this, t, m, a); public new Task<bool> DisplayAlertAsync(string t, string m, string a, string c) => TriarDialogs.ExibirAsync(this, t, m, a, c); }
public partial class EscolhaModoPage { public new Task<bool> DisplayAlertAsync(string t, string m, string a) => TriarDialogs.ExibirAsync(this, t, m, a); public new Task<bool> DisplayAlertAsync(string t, string m, string a, string c) => TriarDialogs.ExibirAsync(this, t, m, a, c); }
public partial class HistoricoPage { public new Task<bool> DisplayAlertAsync(string t, string m, string a) => TriarDialogs.ExibirAsync(this, t, m, a); public new Task<bool> DisplayAlertAsync(string t, string m, string a, string c) => TriarDialogs.ExibirAsync(this, t, m, a, c); }
public partial class HomePage { public new Task<bool> DisplayAlertAsync(string t, string m, string a) => TriarDialogs.ExibirAsync(this, t, m, a); public new Task<bool> DisplayAlertAsync(string t, string m, string a, string c) => TriarDialogs.ExibirAsync(this, t, m, a, c); }
public partial class LoginPage { public new Task<bool> DisplayAlertAsync(string t, string m, string a) => TriarDialogs.ExibirAsync(this, t, m, a); public new Task<bool> DisplayAlertAsync(string t, string m, string a, string c) => TriarDialogs.ExibirAsync(this, t, m, a, c); }
public partial class ResultadoPage { public new Task<bool> DisplayAlertAsync(string t, string m, string a) => TriarDialogs.ExibirAsync(this, t, m, a); public new Task<bool> DisplayAlertAsync(string t, string m, string a, string c) => TriarDialogs.ExibirAsync(this, t, m, a, c); }
public partial class SobrePage { public new Task<bool> DisplayAlertAsync(string t, string m, string a) => TriarDialogs.ExibirAsync(this, t, m, a); public new Task<bool> DisplayAlertAsync(string t, string m, string a, string c) => TriarDialogs.ExibirAsync(this, t, m, a, c); }
public partial class TriagemPage { public new Task<bool> DisplayAlertAsync(string t, string m, string a) => TriarDialogs.ExibirAsync(this, t, m, a); public new Task<bool> DisplayAlertAsync(string t, string m, string a, string c) => TriarDialogs.ExibirAsync(this, t, m, a, c); }
